R/group_by_coalesce.R
R/read_scrape_data.R
man/group_by_coalesce.Rd

made `group_by_coalesce` a lil better by adding a faster non-debug option
```
> system.time(read_scrape_data(TRUE, debug = TRUE))
Base data frame contains 55425 rows.
Coalesced data frame contains 51547 rows.
Named data frame contains 51547 rows.
Pop data frame contains 51547 rows.
user  system elapsed 
566.520   0.345 569.451 
There were 50 or more warnings (use warnings() to see the first 50)
> system.time(read_scrape_data(TRUE, debug = FALSE))
user  system elapsed 
10.112   0.040  11.272 
```

feature: group by coalesce speed up to help read_scrape_data

---

R/read_fac_info.R

Just setting column types explicitly! (Needed for the crosswalk process to avoid issues with column type conflicts)

Specified column types

---

R/clean_facility_name.R
R/read_fac_spellings.R

No more column name changes pretty please, my brain hurts. 
We replaced `Is.Federal` with `Jurisdiction` in fac_spellings so everything broken again. I just replaced the flag with explicit jurisdiction values - would love another set of eyes making sure I didn't mess anything up!

Replaced Is.Federal with Jurisdiction

---

R/read_scrape_data.R
R/reorder_cols.R

Followed Hope's suggestion re: this issue: https://github.com/uclalawcovid19behindbars/behindbarstools/issues/63. 
Variable order is now: 
* Variables in Google Sheet 
* Other variables we scrape but don't report (`Residents.Population`, `Residents.Tested`) 
* Everything else

Updated read_scrape column order

---

R/read_fac_info.R
R/read_fac_spellings.R

For the Github as a Database(™) csv version control for the facility crosswalks, we're appending rows without column names to the existing files to track differences with commits. 
With that, I think we should have explicit `select` statements when we read the files to make sure we know exactly what columns we're reading and in what order. I also updated spellings to add all clean spellings (where `xwalk_name_clean == xwalk_name_raw`). In theory this should be reflected in the raw csv, but I think it's harmless (and potentially useful?) to also do it here.

Made columns explicit

---

R/clean_facility_name.R
R/merge_facility_info.R
R/read_fac_crosswalk.R
R/read_pop_data.R
man/clean_facility_name.Rd
man/merge_facility_info.Rd
man/read_fac_crosswalk.Rd
man/read_pop_data.Rd

- This function now assumes that for all of our data, if a facility is federal, then `Facility` OR `State` OR `Jurisdiction` will contain the word "federal". 
- For non-federal entities, the returned data gets "Jurisdiction" from fac_spellings
- For federal and immigration entities, the returned data gets "Jurisdiction" AND "State" from fac_spellings
- When there is not enough information to get a match, both "Jurisdiction" and "Facility.ID" are returned as NA
Example: 
```
test3 <- tibble(Name = "LEE USP", State = "Virginia", Facility = "Prison", n = 4) %>% # Jurisidction "federal" in xwalk, but not informative enough to get a match
add_row(Name = "LEE USP", State = "federal", Facility = "Prison", n = 2001) # Jurisidction "federal" in xwalk
(out <- clean_facility_name(test3))
Name …
```

Fix fac_spellings merge ambiguity on jurisdiction

---

R/read_scrape_data.R
R/reorder_cols.R

bug fix for read_scrape_data returning an empty source col and just a safer read_csv call similar to Hopes recent PR

fix: scrape cols types

---

R/read_scrape_data.R
man/read_scrape_data.Rd

fill in the last observed value that was not NA  when read scrape data is latest so that when we miss part of states scrape like CA or when PA takes their dashboard down for a month we are still reporting recent data  within a given window specified by the user. Defaults to 31 days.
A downside to this is that read scrape data now takes a bit longer when `all_dates` equals false :/. No speed change when `all_dates` is true

update: read scrape data not all dates fills in latest data with last value

---

R/read_fac_info.R
R/reorder_cols.R

This PR will enable usage of the new `ICE.Field.Office` column added in by [this PR](https://github.com/uclalawcovid19behindbars/facility_data/pull/35). Should only be merged to master after the other PR has been merged otherwise it all breaks.

update: save ICE Field Office col in fac info

---

R/read_scrape_data.R
man/read_scrape_data.Rd

Updates to `read_scrape_data` to: 
* Fixes the date mismatch issues (i.e. where we have `Residents.Population` data on 1/1/21 but run the scrapers on 1/2/21 and want to forward fill population data within a time window for a facility). 
* Drops rows where all COVID variables are NA (e.g. where we only have population data) 
A few things to note: 
* Both of these are parameters (`coalesce_pop` and `drop_na_covid`) that default to TRUE. Is that what we want? Are the names descriptive enough? Thought about renaming `coalesce` to `coalesce_facilities` but decided that might break things. 
* I'm using the same window parameter for the `all_dates = FALSE` forward-filling as historical population forward-filling. This feels okay to me, I think? 
* I decided to handle the date window here (as …

Updating read_scrape to match dates

---

R/read_scrape_data.R

Sorry, I forgot to `ungroup()` after grouping by `Facility.ID` and we don't want to be returning grouped objects!

Ungrouping read_scrape_data() 

---

R/calc_aggregate_counts.R
man/calc_aggregate_counts.Rd

Updated the aggregation function to handle vaccine numbers in a more comparable way. Now when data is missing for vaccines administered it is replaced by initiated. If initiated is also missing then it is replaced by completed. This way Completed and Initiated should never be more than Administered.  
In addition include a column in the aggregation that has the agencies that are not reporting data.
[demo](https://docs.google.com/spreadsheets/d/1MCiyyaz1PtQX_AZ5sMRUOIOttbi8nqIvXCcPt4j4RIo/edit?usp=sharing) of the output with selected columns.

update: add vaccine handling to aggregation

---

R/calc_aggregate_counts.R
man/calc_aggregate_counts.Rd

Allow for TS comparisons of aggregate variables and comparisons to MP/AP data. In addition, changes keep date variables so that we can start to write the date to the sate totals sheet. In order to get time series data you must use the `all_dates` parameter similar to other functions
```
calc_aggregate_counts(all_dates = TRUE)
```

update: ts agg counts and keep date

---

R/group_by_coalesce.R

Test data set below. This change removes warning when there are multiple non-NA and identical values in a group, and doesn't use the `comb_vector` method for these cases. I think this will speed up `read_scrape_data`, although I didn't do any benchmarking
```
df_safe <- tibble(
A=c(1,1,2,2,2),
B=c(2,3,NA,NA,4),
C=c("cat",NA,"samestring","samestring","samestring"),
D=c(NA,2,3,NA,NA),
E=c(18,18,NA,4,NA))
```

chore: rm warning when group-wise value is all same and non-NA

---

R/calc_aggregate_counts.R

Because of the wording on our website it probably makes more sense to prioritize the vaccines initiated rather than other variables for aggregates. In order to get this to show up on the website we will need to ping hyperobject to change the variable that they are reading from `Vadmin` to `Initiated`. Nothing should break before notifying hyperobject.

update: vacc agg fix

---

R/theme_behindbars.R
man/theme_behindbars.Rd

Minor gripe: the axis, text, etc. color (`#555526`) in `theme_behindbars` makes plots look low-resolution (especially in slide decks, reports, etc.). Proposing moving that to a parameter to make it easier to make those a true black. 
```
p + theme_behindbars()
```
```
p + theme_behindbars(base_color = "black")
```

update: add base_color param to theme

---

DESCRIPTION
R/calc_aggregate_counts.R
R/read_scrape_data.R
R/reorder_cols.R
man/read_scrape_data.Rd

PR for changes in read scrape data which addresses the following issues
- Code base moved over to data table which improves speed of function by 4x
- Allows for long data returns which allows us to better preserve date of pulled data which was getting overwritten  with wide data
- Fixes issues in calc_aggergate where old statewide vaccine numbers were being prioritized
- When only recent wide data is returned removes redundant counts where both statewide and non-statewide values were collected
- Coalescing always happens now and you provide the function as a user defaults to sum_na_rm
- Reconciles old vs new scraper when both are collecting data at the same time (prioritizes old scraper)
- Reconciles dedicated vs non-dedicated population data  (prioritizes dedicated)
Draw back is the …

New long read scrape

---

R/read_scrape_data.R

This fixes the issue Hope was running into where facility dates were being repeated because the sources differed. This wasn't an issue for `all_dates = F` but now the fix is applied universally whenever the data is shifted to wide.

fix: debug pivotting wide for when all dates is true

---

R/get_genpop_covid.R
man/get_genpop_covid.Rd

Update to `get_genpop_covid` so that we are reading 2019 census population data, as opposed to 2018, and pulling that number directly from the Census. Think this makes sense to update now given that it will probably be a while before 2020 census population counts are released. Biggest change was in the return object which had a column labeled `General.Population2018` which is now labeled simply `General.Population`.

update: read 2019 pop data for general pop for get_genpop_covid

---

R/ExtractTable.R

Little patch to remove the png tempfile created in `ExtractTable()`. Overwriting the same tempfile was messy because R adds a hash string in the file path to make sure the names are unique – and I couldn't find a good way around this. But this effectively does the same thing.

fix: unclog tempfile space

---

R/calc_aggregate_counts.R

I think we should remove `.Vadmin` from the vaccine collapsing now that we're showing rates. This only affects one state (Tennessee) – we've confirmed that every other state reports either `.Initiated` or `.Completed`!

update: remove vadmin from vaccine collapse

---

R/clean_facility_name.R

Example using both manually-collected and scraper-collected youth data: 
`dat <- tibble(Name = c("OKEECHOBEE SEX OFFENDER FACILITY YOUTH FACILITY FLORIDA", "AARON COHN RYDC YOUTH"), State = c("", "Georgia”), jurisdiction_scraper = c("youth", "state"))`
The way this works is that manually-collected youth facilities are assigned the jurisdiction_scraper `youth`, whereas scraper-collected youth facilities are assigned `state` or `county` jurisdiction directly in the scraper as per usual. 
Depends on changes implemented here: https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/pull/268/files

Update for manually collected youth facilities 

---

R/GLOBALS.R
R/alt_aggregate_counts.R
R/calc_aggregate_counts.R
R/read_mpap_data.R
R/read_scrape_data.R
man/alt_aggregate_counts.Rd
man/calc_aggregate_counts.Rd
man/read_mpap_data.Rd
man/read_mpap_pop_data.Rd
man/read_scrape_data.Rd

Opening this up as a draft PR re: #112. Code changes are really minor – just need to make sure we're all on board with this approach! 
One thing that I could go either way on (also mentioned in the issue) is whether to let window be a parameter, but then have something like: 
```
if (!is.null(window)){
warning("Window has been depreciated as a parameter. Including all data later than 2021-06-01 instead. Specify a date_cutoff to change this threshold.")
```
I think it's probably good code practice to do so, but Hope brought up that it could also be confusing.

update: switch to date_cutoff

---

R/calc_aggregate_counts.R
man/calc_aggregate_counts.Rd

Addresses this and also sort of this
- https://github.com/uclalawcovid19behindbars/behindbarstools/issues/123
- https://github.com/uclalawcovid19behindbars/behindbarstools/issues/121
I realized I don't know what's causing the `alt_aggregate_counts` issue cited here: https://github.com/uclalawcovid19behindbars/behindbarstools/issues/123. Since we filter to Web.Group = "Prison" (`pri_df`) before merging with MP data and doing the case_when stuff, I'm not sure if this issue is relevant to `alt_aggregate_counts`. Would love someone to set me straight if I'm being slow here!

Filter out youth facilities 
